"""Updating foreign key label to lesson_id in Exercise model.

Revision ID: 0f9832bb574c
Revises: 755b631f985a
Create Date: 2021-06-20 18:00:30.425814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9832bb574c'
down_revision = '755b631f985a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'lesson', ['lesson_id'], ['id'])
    op.drop_column('exercise', 'lesson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('lesson', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'lesson', ['lesson'], ['id'])
    op.drop_column('exercise', 'lesson_id')
    # ### end Alembic commands ###
