"""empty message

Revision ID: 3e31e5797606
Revises: a60fb0f70d24
Create Date: 2022-03-26 21:22:44.690700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e31e5797606'
down_revision = 'a60fb0f70d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'title')
    # ### end Alembic commands ###
