"""added_repetition_required

Revision ID: 724a3138b375
Revises: ce1819de10b9
Create Date: 2022-09-05 20:21:20.303686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724a3138b375'
down_revision = 'ce1819de10b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lesson_exercise_progress', sa.Column('repetition_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lesson_exercise_progress', 'repetition_required')
    # ### end Alembic commands ###
