"""adjusting title in exercise model

Revision ID: adda1eb5ea4c
Revises: 3e31e5797606
Create Date: 2022-03-27 19:52:16.558458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adda1eb5ea4c'
down_revision = '3e31e5797606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'title')
    # ### end Alembic commands ###
